// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.redbarn.shares;

import com.redbarn.shares.Co;
import com.redbarn.shares.CoDataOnDemand;
import com.redbarn.shares.CoIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CoIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CoIntegrationTest: @Transactional;
    
    @Autowired
    private CoDataOnDemand CoIntegrationTest.dod;
    
    @Test
    public void CoIntegrationTest.testCountCoes() {
        Assert.assertNotNull("Data on demand for 'Co' failed to initialize correctly", dod.getRandomCo());
        long count = Co.countCoes();
        Assert.assertTrue("Counter for 'Co' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CoIntegrationTest.testFindCo() {
        Co obj = dod.getRandomCo();
        Assert.assertNotNull("Data on demand for 'Co' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Co' failed to provide an identifier", id);
        obj = Co.findCo(id);
        Assert.assertNotNull("Find method for 'Co' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Co' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CoIntegrationTest.testFindAllCoes() {
        Assert.assertNotNull("Data on demand for 'Co' failed to initialize correctly", dod.getRandomCo());
        long count = Co.countCoes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Co', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Co> result = Co.findAllCoes();
        Assert.assertNotNull("Find all method for 'Co' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Co' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CoIntegrationTest.testFindCoEntries() {
        Assert.assertNotNull("Data on demand for 'Co' failed to initialize correctly", dod.getRandomCo());
        long count = Co.countCoes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Co> result = Co.findCoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Co' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Co' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CoIntegrationTest.testFlush() {
        Co obj = dod.getRandomCo();
        Assert.assertNotNull("Data on demand for 'Co' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Co' failed to provide an identifier", id);
        obj = Co.findCo(id);
        Assert.assertNotNull("Find method for 'Co' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCo(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Co' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CoIntegrationTest.testMergeUpdate() {
        Co obj = dod.getRandomCo();
        Assert.assertNotNull("Data on demand for 'Co' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Co' failed to provide an identifier", id);
        obj = Co.findCo(id);
        boolean modified =  dod.modifyCo(obj);
        Integer currentVersion = obj.getVersion();
        Co merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Co' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CoIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Co' failed to initialize correctly", dod.getRandomCo());
        Co obj = dod.getNewTransientCo(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Co' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Co' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Co' identifier to no longer be null", obj.getId());
    }
}
