// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.redbarn.shares;

import com.redbarn.shares.TradingDay;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TradingDay_Roo_Configurable {
    
    declare @type: TradingDay: @Configurable;
    
}
